# -*- coding: utf-8 -*-
"""AI RESEARCH POWER STATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VeW7psc_aAEt-fGKqqGpl7aAeb-fvsmV
"""

!pip install datasets

from datasets import load_dataset

dataset = load_dataset("CShorten/ML-ArXiv-Papers",split='train')

print(dataset)

dataset[0]

import pandas as pd

df=pd.DataFrame(dataset)
df

df.columns

df=df[['title','abstract']]

df

df.shape

df=df.head(15000)

df.isnull().sum()

df['paper_text']=df['title']+" "+df["abstract"]

df["paper_text"].head()

type(df[["paper_text"]])

df[["paper_text"]].head()

print(df["paper_text"].iloc[0])

from sentence_transformers import SentenceTransformer

model=SentenceTransformer("all-MiniLM-L6-v2")

print(type(model))

sample_text=df["paper_text"].iloc[0]
sample_text

df['paper_text']=df['paper_text'].fillna("")

df['paper_text']=df['paper_text'].str.replace('\n',"",regex=False)

df['paper_text']=df['paper_text'].str.strip()

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

sample_text = df["abstract"].iloc[0]

embedding = model.encode(sample_text)

print(embedding.shape)

import os
import numpy as np


embedding_file = "paper_embeddings.npy"

if os.path.exists(embedding_file):
    print("Loading Saved embeddings...")
    embedding = np.load(embedding_file)
else:
    print("Generating embeddings...")

    embedding = model.encode(df["paper_text"].tolist(), batch_size=32, show_progress_bar=True)
    np.save(embedding_file, embedding)
    print("Embeddings saved successfully!")

print(embedding.shape)

embedding[:56]

print(df.columns)

texts = df["paper_text"].head(5).tolist()
print(type(texts))

print(type(texts[0]))
print(texts[0])

texts = df["paper_text"].head(5).tolist()

print(type(texts))
print(type(texts[0]))

df['paper_text'] = df['paper_text'].str.replace('\n', "", regex=False)
df['paper_text'] = df['paper_text'].str.strip()

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

sample_embeddings = model.encode(texts)

print(sample_embeddings.shape)

from sklearn.metrics.pairwise import cosine_similarity

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(
    sample_embeddings[0].reshape(1, -1),
    sample_embeddings
)

print(similarity)

similarity = cosine_similarity(
    sample_embeddings[0].reshape(1, -1),
    sample_embeddings[1].reshape(1,-1)
)

print(similarity)

for i in range(1,5):
  sim=cosine_similarity(sample_embeddings[0].reshape(1,-1),sample_embeddings[i].reshape(1,-1))
  print(sim)

"""GENERATE FULL **EMBEDDING**"""

texts = df["paper_text"].head(5).tolist()

sample_embeddings = model.encode(texts)

print(sample_embeddings.shape)

embedding.dtype

!pip install faiss-cpu

import faiss

faiss.normalize_L2(embedding)

index = faiss.IndexFlatIP(384)

index.add(embedding)

import os
import faiss


index_path = "paper_faiss.index"

if os.path.exists(index_path):
    print("Loading existing FAISS index")
    index = faiss.read_index(index_path)
else:
    print("Creating new FAISS index")

    index = faiss.IndexFlatIP(384)
    index.add(embedding)
    faiss.write_index(index, index_path)
    print("FAISS index saved successfully")

print(index.ntotal)

import faiss
import numpy as np

embedding = embedding.astype(np.float32)

faiss.normalize_L2(embedding)

dimension = embedding.shape[1]

index = faiss.IndexFlatIP(dimension)

index.add(embedding)

print(index.ntotal)

def search_paper(query,k=5):
  query_embedding=model.encode([query])
  query_embedding=query_embedding.reshape(1,-1)
  faiss.normalize_L2(query_embedding)

def search_paper(query,k=5):
  query_embedding=model.encode([query])
  query_embedding=query_embedding.reshape(1,-1)
  faiss.normalize_L2(query_embedding)
  index.search(query_embedding,5)

print(df.iloc[0]["title"])

print(df.iloc[-1]["title"])

print(df.iloc[0]["abstract"])

print(df.iloc[-1]["abstract"])

def search_paper(query,k=5):
  query_embedding=model.encode([query])
  query_embedding=query_embedding.reshape(1,-1)
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  return D,I

D,I=search_paper("deep learning for mediccal image analysis")
print(D)
print(I)

def search_paper(query,k=5):
  query_embedding=model.encode([query])
  query_embedding=query_embedding.reshape(1,-1)
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score,idx in zip(D[0],I[0]):
    print("Similarity score",score)
    print("Title",df.iloc[idx]["title"])
    print("Title",df.iloc[idx]["abstract"][:500])

search_paper("deep learning for mediccal image analysis")

!pip install transformers==4.46.3

from transformers import pipeline
summarizer=pipeline(
    "summarization",
    model="facebook/bart-large-cnn"
)

type(summarizer)

summary=summarizer(df.iloc[0]["abstract"],max_length=120,min_length=40)
print(summary)

type(summary)

type(summary[0])

summary[0]["summary_text"]

for score,idx in zip(D[0],I[0]):
    print("Similarity score",score)
    print("Title",df.iloc[idx]["title"])
    print("Title",df.iloc[idx]["abstract"][:500])
    summary=summarizer(df.iloc[idx]["abstract"],max_length=120,min_length=40)
    print(summary)
    print(summary[0]["summary_text"])
    print()

def search_and_summarize(query,k=5):
  query_embedding=model.encode([query])
  query_embedding=query_embedding.reshape(1,-1)
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)

  for score,idx in zip(D[0],I[0]):
    print("Similarity score",score)
    print("Title",df.iloc[idx]["title"])
    print("Title",df.iloc[idx]["abstract"][:500])
    summary=summarizer(df.iloc[idx]["abstract"],max_length=120,min_length=40)
    print(summary)
    print(summary[0]["summary_text"])
    print()

search_and_summarize("deep learning for mediccal image analysis")

!pip install keybert==0.8

from keybert import KeyBERT

kw_model=KeyBERT()

text=df.iloc[0]["abstract"]
keywords=kw_model.extract_keywords(text)

print(keywords)

from transformers import pipeline

classifier = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli"
)

from keybert import KeyBERT

kw_model = KeyBERT()

keywords = kw_model.extract_keywords(
    ['abstract'],
    top_n=10
)

from transformers import pipeline

classifier = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli"
)

text = "deep learning for medical image analysis"

result = classifier(
    text,
    candidate_labels=[
        "Programming Language",
        "Framework",
        "AI Technique",
        "Medical Concept",
        "Research Area"
    ]
)

print(result)

import gradio as gr
from transformers import pipeline

classifier = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli"
)

DEFAULT_LABELS = [
    "Programming Language",
    "Framework",
    "AI Technique",
    "Model Architecture",
    "Medical Concept",
    "Research Area",
    "Database",
    "Cloud Platform",
    "Deployment Tool"
]

def classify_text(text):
    result = classifier(
        text,
        candidate_labels=DEFAULT_LABELS
    )

    return {
        label: score
        for label, score in zip(
            result["labels"],
            result["scores"]
        )
    }

interface = gr.Interface(
    fn=classify_text,
    inputs=gr.Textbox(
        lines=2,
        placeholder="Enter keyword or text..."
    ),
    outputs=gr.Label(num_top_classes=5),
    title="AI  Classifier",
    description="Classify research concepts automatically."
)

interface.launch()